import Link from "next/link";
import { getCurrentAdmin } from "../auth";

export const dynamic = "force-dynamic";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ error?: string; reason?: string }> }) {
  const email = await getCurrentAdmin();
  const { error, reason } = await searchParams;
  if (!email) return <main className="admin-shell"><Link className="admin-brand" href="/">← Burt Baptist Church</Link><section className="login-card"><p className="eyebrow">Staff portal</p><h1>Welcome back.</h1><p>Sign in to update church information and publish sermons. On a new site, the first sign-in creates the first staff account.</p>{error === "invalid-login" && <p className="login-error">That email or password was not recognized. New staff passwords must be at least 6 characters.</p>}{error === "database" && <p className="login-error">The staff table could not be reached. {reason ? `D1 reported: ${reason}` : "Confirm this Worker is connected to the burtbaptistchurch D1 database."}</p>}{error === "d1-binding" && <p className="login-error">This deployed Worker does not have its D1 database binding. Redeploy the latest main branch.</p>}<form action="/api/auth/login" method="post" className="login-form"><label>Email address<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" minLength={6} autoComplete="current-password" required /></label><button className="button button-dark" type="submit">Sign in <span>→</span></button></form><small>Having trouble? Contact your site administrator.</small></section></main>;
  return <main className="admin-shell"><header className="admin-header"><Link className="admin-brand" href="/">← Burt Baptist Church</Link><div className="admin-account"><span>Signed in as {email}</span><form action="/api/auth/logout" method="post"><button type="submit">Sign out</button></form></div></header><section className="admin-intro"><p className="eyebrow">Staff portal</p><h1>Keep the church<br /><i>connected.</i></h1><p>Update the Sunday welcome, publish a quick site notice, or add the latest message below.</p></section><section className="admin-grid"><form className="admin-card" action="/api/admin/content" method="post"><p className="eyebrow">Website update</p><h2>Sunday welcome</h2><label>Headline<input name="title" required defaultValue="You belong here" /></label><label>Message<textarea name="body" required defaultValue="Join us this Sunday at 10:30 AM. We can’t wait to meet you." /></label><button className="button button-dark" type="submit">Publish update <span>→</span></button></form><form className="admin-card" action="/api/admin/sermons" method="post" encType="multipart/form-data"><p className="eyebrow">Sermon library</p><h2>Add a message</h2><label>Message title<input name="title" required /></label><label>Speaker<input name="speaker" required placeholder="Pastor Mark" /></label><label>Service date<input name="sermonDate" type="date" required /></label><label>Description<textarea name="description" placeholder="A short summary for listeners" /></label><label>Outline text<textarea name="outline" placeholder="Paste the sermon outline here. Separate paragraphs with a blank line." /></label><label>Audio file<input name="audio" type="file" accept="audio/*" /></label><label>Outline PDF<input name="pdf" type="file" accept="application/pdf,.pdf" /></label><label>Or video / message link<input name="mediaUrl" type="url" placeholder="https://..." /></label><button className="button button-dark" type="submit">Publish message <span>→</span></button></form></section><p className="admin-note">Your staff session is secured with an HTTP-only cookie. Use the Sign out button when you are finished.</p></main>;
}
