import Link from "next/link";
import { getPageEntry } from "../../db/content";

export const metadata = { title: "About Us | Burt Baptist Church" };

export default async function AboutPage() {
  const about = await getPageEntry("about");
  return <main className="inner-page"><header className="inner-header"><Link className="brand logo-only" href="/" aria-label="Burt Baptist Church home"><img src="/burt-baptist-logo.png" alt="Burt Baptist Church" /></Link><nav><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/sermons">Sermons</Link><Link href="/contact">Contact</Link></nav></header><section className="page-hero"><p className="eyebrow light">About Burt Baptist</p><h1>Faith for every<br /><i>season of life.</i></h1></section><section className="page-content"><div><p className="eyebrow">{about?.eyebrow ?? "Our mission"}</p><h2>{about?.title ?? "Helping people grow in their relationship with God."}</h2></div><div><p>{about?.body ?? "At Burt Baptist Church, we seek to strengthen meaningful relationships in family life and community. Join us each Sunday to experience the warmth of faith and the strength of our church family."}</p><p>We use the whole Word of God—the Old and New Testaments—as the foundation for our faith, and we strive to put its teaching into practice at home, at work, and every day.</p></div></section><section className="service-times"><div><p className="eyebrow light">Worship with us</p><h2>Sunday services</h2></div><div className="times"><p><b>Morning service</b><span>11:00 AM</span></p><p><b>Evening service</b><span>6:00 PM</span></p></div></section><section className="first-visit"><p className="eyebrow">First time here?</p><h2>Come as you are.<br /><i>We&apos;ll be glad to meet you.</i></h2><p>No matter where you come from or where you are in your spiritual journey, we want to come alongside you, encourage you, and help you live a life that blesses the world.</p><Link className="button button-dark" href="/contact">Plan your visit <span>→</span></Link></section></main>;
}
