import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Burt Baptist Church | Burt, Michigan", description: "A place to belong, grow, and serve in Burt, Michigan." };

const sermons = [
  { date: "JUL 20", title: "When Hope Has a Name", speaker: "Pastor Mark" },
  { date: "JUL 13", title: "Faith for the Everyday", speaker: "Pastor Mark" },
  { date: "JUL 06", title: "A Table Big Enough", speaker: "Guest Speaker" },
];

export default function Home() { return <main>
  <section className="hero" id="home"><nav className="nav shell" aria-label="Primary navigation"><Link className="brand" href="#home" aria-label="Burt Baptist Church home"><span className="brand-mark">B</span><span>Burt <em>Baptist</em></span></Link><div className="nav-links"><a href="#visit">Plan a visit</a><a href="#sermons">Watch</a><a href="#about">About</a></div><a className="button button-light nav-give" href="#give">Give</a></nav><div className="hero-grid shell"><div className="hero-copy"><p className="eyebrow light">Burt, Michigan</p><h1>Come as you are.<br /><i>Leave encouraged.</i></h1><p className="hero-text">A church family learning to follow Jesus together—with honest faith, open arms, and room for your story.</p><div className="hero-actions"><a className="button button-gold" href="#visit">Plan your visit <span>→</span></a><a className="text-link light" href="#sermons">Watch a message <span>↗</span></a></div></div><aside className="service-card"><p className="eyebrow">This Sunday</p><div className="rule" /><h2>Worship at<br />10:30 AM</h2><p>Sunday School · 9:30 AM<br />A relaxed, welcoming place for every age.</p><a href="#visit">Get directions <span>→</span></a></aside></div><div className="hero-orbit orbit-a" /><div className="hero-orbit orbit-b" /></section>
  <section className="welcome shell" id="about"><p className="eyebrow">You belong here</p><div className="welcome-grid"><h2>Church is not a place to have it all together. <i>It&apos;s a place to grow.</i></h2><div><p>Whether you&apos;ve been in church your whole life or you&apos;re still figuring out what you believe, you&apos;ll find people here who are glad you came.</p><a className="text-link" href="#visit">What to expect <span>→</span></a></div></div></section>
  <section className="visit" id="visit"><div className="shell visit-grid"><div className="visit-art" aria-hidden="true"><div className="sun" /><div className="door door-one" /><div className="door door-two" /></div><div className="visit-copy"><p className="eyebrow">Your first Sunday</p><h2>We saved you<br />a <i>seat.</i></h2><p>Walk in, grab a coffee, and let us help you get settled. Dress comfortably. Bring your questions. Bring your kids—there&apos;s a place for them too.</p><div className="visit-list"><span>01</span><p><b>Arrive a few minutes early</b><br />We&apos;ll help you find your way around.</p><span>02</span><p><b>Stay for a while</b><br />Meet someone new after service.</p></div><a className="button button-dark" href="https://maps.google.com/?q=Burt+Baptist+Church+Burt+MI" target="_blank" rel="noreferrer">Find us on the map <span>↗</span></a></div></div></section>
  <section className="sermons shell" id="sermons"><div className="section-heading"><div><p className="eyebrow">Latest messages</p><h2>Keep listening.</h2></div><a className="text-link" href="#all-messages">Browse all messages <span>→</span></a></div><div className="sermon-grid">{sermons.map((sermon, index) => <article className="sermon" key={sermon.title}><div className={`sermon-image image-${index + 1}`}><button aria-label={`Play ${sermon.title}`}>▶</button></div><p className="sermon-meta">{sermon.date} <span>·</span> {sermon.speaker}</p><h3>{sermon.title}</h3><a href="#all-messages">Listen now <span>→</span></a></article>)}</div></section>
  <section className="quote"><div className="shell"><span className="quote-mark">“</span><blockquote>We want to be a people who make the hope of Jesus <i>feel close.</i></blockquote><p>— OUR HEART FOR BURT</p></div></section>
  <section className="give shell" id="give"><div><p className="eyebrow">Generosity changes things</p><h2>Give with<br /><i>purpose.</i></h2></div><div><p>Your giving helps us care for our neighbors, invest in the next generation, and share the good news of Jesus in our community.</p><a className="button button-dark" href="#online-giving">Give online <span>→</span></a></div></section>
  <footer><div className="shell footer-grid"><div><Link className="brand footer-brand" href="#home"><span className="brand-mark">B</span><span>Burt <em>Baptist</em></span></Link><p>A church family in Burt, Michigan.</p></div><div><p className="footer-label">Find us</p><p>12222 E. Burt Road<br />Burt, MI 48417</p></div><div><p className="footer-label">Gather with us</p><p>Sundays · 10:30 AM<br />Sunday School · 9:30 AM</p></div><div><p className="footer-label">Stay connected</p><a href="mailto:hello@burtbaptistchurch.org">hello@burtbaptistchurch.org</a><br /><Link href="/admin">Staff login</Link></div></div><div className="shell copyright">© {new Date().getFullYear()} Burt Baptist Church <span>Made with care for our community.</span></div></footer>
</main>; }
