import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Burt Baptist Church | Burt, Michigan", description: "A place to belong, grow, and serve in Burt, Michigan." };

const sermons = [
  { date: "JUN 07", title: "It Just Keeps Getting Better!", speaker: "Burt Baptist Church" },
  { date: "JUN 07", title: "A Victorious Christian Life!", speaker: "Burt Baptist Church" },
  { date: "MAY 31", title: "How Long, Lord?", speaker: "Burt Baptist Church" },
];

export default function Home() { return <main>
<section className="hero" id="home"><div className="hero-photo" aria-hidden="true" /><nav className="nav shell" aria-label="Primary navigation"><Link className="brand logo-only" href="#home" aria-label="Burt Baptist Church home"><img src="/burt-baptist-logo.png" alt="Burt Baptist Church" /></Link><div className="nav-links"><a href="#visit">Plan a visit</a><a href="#sermons">Sermons</a><a href="#about">Our church</a></div><a className="button button-light nav-give" href="#give">Give online</a></nav><div className="hero-grid shell"><div className="hero-copy"><p className="eyebrow light">Loving God · Loving Others · Making Disciples</p><h1>A place to <i>grow</i><br />in faith.</h1><p className="hero-text">At Burt Baptist Church, we help people explore their relationship with God and build meaningful relationships in family and community.</p><div className="hero-actions"><a className="button button-gold" href="#visit">Plan your visit <span>→</span></a><a className="text-link light" href="#sermons">Hear a sermon <span>↗</span></a></div></div><aside className="service-card"><p className="eyebrow">You are welcome here</p><div className="rule" /><h2>Join us<br />this Sunday</h2><p>Experience the warmth of faith and the strength of our community.</p><a href="#visit">Find Burt Baptist <span>→</span></a></aside></div></section>
  <section className="welcome shell" id="about"><p className="eyebrow">Welcome to Burt Baptist</p><div className="welcome-grid"><h2>Discover a <i>victorious Christian life.</i></h2><div><p>We are a local church family committed to loving God, loving others, and making disciples. Whether you have grown up in church or are just beginning to explore faith, there is a place for you here.</p><a className="text-link" href="#visit">Plan your first visit <span>→</span></a></div></div></section>
  <section className="visit" id="visit"><div className="shell visit-grid"><div className="visit-art" aria-hidden="true"><div className="sun" /><div className="door door-one" /><div className="door door-two" /></div><div className="visit-copy"><p className="eyebrow">Your first Sunday</p><h2>We saved you<br />a <i>seat.</i></h2><p>Walk in, grab a coffee, and let us help you get settled. Dress comfortably. Bring your questions. Bring your kids—there&apos;s a place for them too.</p><div className="visit-list"><span>01</span><p><b>Arrive a few minutes early</b><br />We&apos;ll help you find your way around.</p><span>02</span><p><b>Stay for a while</b><br />Meet someone new after service.</p></div><a className="button button-dark" href="https://maps.google.com/?q=Burt+Baptist+Church+Burt+MI" target="_blank" rel="noreferrer">Find us on the map <span>↗</span></a></div></div></section>
  <section className="sermons shell" id="sermons"><div className="section-heading"><div><p className="eyebrow">Latest messages</p><h2>Keep listening.</h2></div><a className="text-link" href="#all-messages">Browse all messages <span>→</span></a></div><div className="sermon-grid">{sermons.map((sermon, index) => <article className="sermon" key={sermon.title}><div className={`sermon-image image-${index + 1}`}><button aria-label={`Play ${sermon.title}`}>▶</button></div><p className="sermon-meta">{sermon.date} <span>·</span> {sermon.speaker}</p><h3>{sermon.title}</h3><a href="#all-messages">Listen now <span>→</span></a></article>)}</div></section>
  <section className="quote"><div className="shell"><span className="quote-mark">“</span><blockquote>We want to be a people who make the hope of Jesus <i>feel close.</i></blockquote><p>— OUR HEART FOR BURT</p></div></section>
  <section className="give shell" id="give"><div><p className="eyebrow">Generosity changes things</p><h2>Give with<br /><i>purpose.</i></h2></div><div><p>Your giving helps us care for our neighbors, invest in the next generation, and share the good news of Jesus in our community.</p><a className="button button-dark" href="#online-giving">Give online <span>→</span></a></div></section>
<footer><div className="shell footer-grid"><div><Link className="brand logo-only footer-brand" href="#home"><img src="/burt-baptist-logo.png" alt="Burt Baptist Church" /></Link><p>A church family in Burt, Michigan.</p></div><div><p className="footer-label">Find us</p><p>1200 W. Burt Road<br />Burt, MI 48417</p></div><div><p className="footer-label">Gather with us</p><p>Sunday worship<br />Everyone is welcome</p></div><div><p className="footer-label">Stay connected</p><a href="mailto:hello@burtbaptistchurch.org">hello@burtbaptistchurch.org</a><br /><Link href="/admin">Staff login</Link></div></div><div className="shell copyright">© {new Date().getFullYear()} Burt Baptist Church <span>Made with care for our community.</span></div></footer>
</main>; }
